// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet() {
  return window['go']['main']['App']['Greet']();
}

export function Log(arg1) {
  return window['go']['main']['App']['Log'](arg1);
}
